apiVersion: v1
kind: Service
metadata:
  namespace: supply
  creationTimestamp: null
  labels:
    app: frontend-supp
    app.kubernetes.io/managed-by: Helm
  name: {{ .Values.front.metadata.svcName }}
spec:
  ports:
  - port: {{ .Values.front.service.ports.port }}
    protocol: TCP
    targetPort: {{ .Values.front.service.ports.targetPort  }}
    nodePort: {{ .Values.front.service.ports.NodePort }}
  selector:
    app: frontend-supp
  type: {{ .Values.serviceType.NodePort}} #kijken wat beter werkt, servicetype als global of gespecificeerd in values
status:
  loadBalancer: {}
