apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: supply
  creationTimestamp: null
  labels:
    app: manu-supp
  name: {{ .Values.manuBack.metadata.deployName}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: manu-supp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: manu-supp
    spec:
      containers:
      - image: {{ .Values.manuBack.spec.containers.image}}
        name: {{  .Values.manuBack.spec.containers.name }}
        resources: {}
        env:
        - name: DB_HOST 
          value: "database-svc"
        - name: DB_USER
          value: "root"
        - name: DB_PASS
          value: "root"
        - name: DB_NAME 
          value: "scm_new"
        - name: SECRET_KEY
          valueFrom:
           secretKeyRef:
             name: supply-secret
             key: jwt-key      
status: {}
