apiVersion: v1
kind: Service
metadata:
  namespace: supply
  creationTimestamp: null
  labels:
    app: retail-supp
    app.kubernetes.io/managed-by: Helm
  name: {{ .Values.retailBack.metadata.svcName }}
spec:
  ports:
  - port: {{ .Values.retailBack.service.ports.port }}
    protocol: TCP
    targetPort: {{ .Values.retailBack.service.ports.targetPort  }}
    nodePort: {{ .Values.retailBack.service.ports.NodePort }}
  selector:
    app: retail-supp
  type: {{ .Values.serviceType.NodePort}} 
status:
  loadBalancer: {}
