apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace}}
  creationTimestamp: null
  labels:
    app: retail-supp
    app.kubernetes.io/managed-by: Helm
  name: {{ .Values.retailBack.metadata.svcName }}
spec:
  ports:
  - port: {{ .Values.retailBack.service.ports.port }}
    protocol: TCP
    targetPort: {{ .Values.retailBack.service.ports.targetPort  }}
  selector:
    app: retail-supp
  type: clusterIP
status:
  loadBalancer: {}
